
export enum ErrorCode {
  // Common
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Point
  POINT_POLICY_NOT_SATISFIED = 'POINT_POLICY_NOT_SATISFIED',
  POINT_ALREADY_EARNED = 'POINT_ALREADY_EARNED',
  POINT_AMOUNT_INVALID = 'POINT_AMOUNT_INVALID',

  // Auth / User (나중에 확장)
  UNAUTHORIZED = 'UNAUTHORIZED',
}
